version: 1.0.{build}
branches:
  only:
  - develop
install:
- cmd: appveyor-retry npm install
- cmd: git config --global credential.helper store
- cmd: git config --global credential.helper store
- ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
- cmd: git config --global user.email "kevin@hellotonic.com"
- cmd: git config --global user.name "Deploy Bot"
build_script:
- cmd: npm run deploy

environment:
  access_token:
    secure: gZzyBZAyWnL/SWk510yUo6TWqJPS3irtr/JtrzhM0z9fDscuqNSizPLW+nh+KekO

